/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as ApiProxySplatRouteImport } from './routes/api/proxy.$'
import { Route as AppEmpresaContaIdRouteImport } from './routes/_app.empresa.$contaId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const ApiProxySplatRoute = ApiProxySplatRouteImport.update({
  id: '/api/proxy/$',
  path: '/api/proxy/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEmpresaContaIdRoute = AppEmpresaContaIdRouteImport.update({
  id: '/empresa/$contaId',
  path: '/empresa/$contaId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/admin': typeof AppAdminRoute
  '/empresa/$contaId': typeof AppEmpresaContaIdRoute
  '/api/proxy/$': typeof ApiProxySplatRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AppAdminRoute
  '/': typeof AppIndexRoute
  '/empresa/$contaId': typeof AppEmpresaContaIdRoute
  '/api/proxy/$': typeof ApiProxySplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/admin': typeof AppAdminRoute
  '/_app/': typeof AppIndexRoute
  '/_app/empresa/$contaId': typeof AppEmpresaContaIdRoute
  '/api/proxy/$': typeof ApiProxySplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/empresa/$contaId' | '/api/proxy/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/admin' | '/' | '/empresa/$contaId' | '/api/proxy/$'
  id:
    | '__root__'
    | '/_app'
    | '/_app/admin'
    | '/_app/'
    | '/_app/empresa/$contaId'
    | '/api/proxy/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ApiProxySplatRoute: typeof ApiProxySplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/proxy/$': {
      id: '/api/proxy/$'
      path: '/api/proxy/$'
      fullPath: '/api/proxy/$'
      preLoaderRoute: typeof ApiProxySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/empresa/$contaId': {
      id: '/_app/empresa/$contaId'
      path: '/empresa/$contaId'
      fullPath: '/empresa/$contaId'
      preLoaderRoute: typeof AppEmpresaContaIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEmpresaContaIdRoute: typeof AppEmpresaContaIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppIndexRoute: AppIndexRoute,
  AppEmpresaContaIdRoute: AppEmpresaContaIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ApiProxySplatRoute: ApiProxySplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
